
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package miniJava.parser;

/** CUP generated interface containing symbol constants. */
public interface Tokens {
  /* terminals */
  public static final int O_PAR = 19;
  public static final int SLASH = 36;
  public static final int EQUALS = 27;
  public static final int INTEGER = 41;
  public static final int GREATER = 31;
  public static final int INT = 7;
  public static final int PRINTLN = 45;
  public static final int STRGARG = 47;
  public static final int C_BRAC = 22;
  public static final int LESS = 29;
  public static final int MINUS = 34;
  public static final int STATIC = 5;
  public static final int SEMICOLON = 15;
  public static final int AND = 26;
  public static final int C_PAR = 20;
  public static final int OR = 25;
  public static final int COMMA = 17;
  public static final int CLASS = 2;
  public static final int PLUS = 33;
  public static final int MAIN = 44;
  public static final int ASSIGN = 18;
  public static final int IF = 10;
  public static final int THIS = 13;
  public static final int ID = 43;
  public static final int DOT = 16;
  public static final int O_BRAC = 21;
  public static final int EOF = 0;
  public static final int BOOLEAN = 8;
  public static final int RETURN = 12;
  public static final int TRUE = 40;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int PERCENT = 37;
  public static final int C_BRACK = 24;
  public static final int VOID = 6;
  public static final int O_BRACK = 23;
  public static final int TIMES = 35;
  public static final int ELSE = 11;
  public static final int WHILE = 9;
  public static final int LESS_EQ = 30;
  public static final int FLOAT = 42;
  public static final int PUBLIC = 3;
  public static final int EXTENDS = 4;
  public static final int DIFF = 28;
  public static final int OPP = 38;
  public static final int FALSE = 39;
  public static final int LENGTH = 46;
  public static final int GREATER_EQ = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "PUBLIC",
  "EXTENDS",
  "STATIC",
  "VOID",
  "INT",
  "BOOLEAN",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "THIS",
  "NEW",
  "SEMICOLON",
  "DOT",
  "COMMA",
  "ASSIGN",
  "O_PAR",
  "C_PAR",
  "O_BRAC",
  "C_BRAC",
  "O_BRACK",
  "C_BRACK",
  "OR",
  "AND",
  "EQUALS",
  "DIFF",
  "LESS",
  "LESS_EQ",
  "GREATER",
  "GREATER_EQ",
  "PLUS",
  "MINUS",
  "TIMES",
  "SLASH",
  "PERCENT",
  "OPP",
  "FALSE",
  "TRUE",
  "INTEGER",
  "FLOAT",
  "ID",
  "MAIN",
  "PRINTLN",
  "LENGTH",
  "STRGARG"
  };
}

